version: '3.3'

services:
  db:
    image: postgres:9.5
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=hurumap
      - POSTGRES_PASSWORD=hurumap
      - POSTGRES_DB=${HURUMAP_APP:-hurumap_land}
      - PGUSER=hurumap
      - PGPASSWORD=hurumap

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/src/hurumap-apps
    environment:
      - HURUMAP_APP=${HURUMAP_APP:-hurumap_land}
      - DJANGO_SETTINGS_MODULE=${HURUMAP_APP:-hurumap_land}.settings
      - DATABASE_URL=postgresql://hurumap:hurumap@db:5432/${HURUMAP_APP:-hurumap_land}
      - DJANGO_SECRET_KEY=somethingsecret
      - HURUMAP_URL="http://localhost:8000"
      - PGHOST=db
      - PGDATABASE=${HURUMAP_APP:-hurumap_land}
      - PGUSER=hurumap
      - PGPASSWORD=hurumap
      - USE_MAPIT=True
      - PYTHONUNBUFFERED=True
      - PYTHONDONTWRITEBYTECODE=True
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True} # For testing deploys
