version: '3.3'

services:
  db:
    image: postgres:9.5
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=our_land
      - POSTGRES_PASSWORD=our_land
      - POSTGRES_DB=our_land

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/src/our_land
      - /static:/static
    environment:
      - DATABASE_URL=postgresql://our_land:our_land@db:5432/our_land
      - DJANGO_SECRET_KEY=somethingsecret
      - HURUMAP_URL='http://localhost:8000'
      - PGHOST=db
      - PGDATABASE=our_land
      - PGUSER=our_land
      - PGPASSWORD=our_land
      - PYTHONDONTWRITEBYTECODE="True"
      - HURUMAP_APP_NAME='our_land'
      # - DJANGO_DEBUG=False  # For testing deploys
